version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: asteroid
      MONGO_INITDB_ROOT_PASSWORD: passwerd
      MONGO_INITDB_DATABASE: fs-todo
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
